layout_spectrum: 1
typography_spectrum: 0.7750627
color:
  saturation: 0.5757961
  lightness: 0.2030102
  brandStrength: 0.2863697
  rhythmicContrast: 0.1347647
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: easyfreight
